---
title: "p8105_hw5_km3529"
author: "Karina Myers"
date: "11/10/2020"
output: html_document
---


```{r}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


```{r}
homicide_df = 
  read_csv("data/homicide.csv") %>% 
  mutate(
    city_state = str_c(city, state, sep = "_"), 
    resolved = case_when(
      disposition == "Closed without arrest" ~ "unsolved", 
      disposition == "Open/No arrest" ~ "unsolved", 
      disposition == "Closed by arrest" ~ "solved"
    ) ) %>% 
  select(city_state, resolved) %>% 
  filter(city_state != "Tulse_AL")
  
```

```{r}
aggregate_df = 
  homicide_df %>% 
  group_by(city_state) %>% 
  summarize(
    hom_total = n(), 
    hom_unsolved = sum(resolved == "unsolved")
  )
```

Can I do prop test for a single city 
```{r}
prop.test(
  aggregate_df %>% filter(city_state ==  "Baltimore_MD") %>% pull(hom_unsolved), 
  aggregate_df %>% filter(city_state ==  "Baltimore_MD") %>% pull(hom_total)) %>% 
  broom::tidy()
```

try to iterate... 
```{r}
results_df = 
  aggregate_df %>% 
  mutate(
    prop_tests = map2(.x = hom_unsolved, .y = hom_total, ~prop.test(x = .x, n = .y)), 
    tidy_tests = map(.x = prop_tests, ~broom::tidy(.x))) %>% 
  select(-prop_tests) %>% 
  unnest(tidy_tests) %>%
  select(city_state, estimate, conf.low, conf.high)
```


```{r}
results_df %>% 
  
  ggplot(aes(x = city_state,  y = estimate)) + 
  geom_point()
```




```{r}
city_prop_test = function(df) {
  
  n_unsolved ... 
  n_total... 
}
  
  homicide_df = 
  read_csv("data/homicide.csv") %>% 
  mutate(
    city_state = str_c(city, state, sep = "_"), 
    resolved = case_when(
      disposition == "Closed without arrest" ~ "unsolved", 
      disposition == "Open/No arrest" ~ "unsolved", 
      disposition == "Closed by arrest" ~ "solved"
    ) ) %>% 
  select(city_state, resolved) %>% 
  filter(city_state != "Tulse_AL") %>% 
  nest(data = resolved)
```





